### ISSUE TITLE
Exclamation mark error

### ISSUE THREAD

**Issue by AlejandroColinaPew** [jonschlinkert/strip-comments#39]
File: uncomnt.js
```   
    var strip = require('strip-comments');
    var str = strip('Hey! // foo');
    console.log(str);
```
Command:
```
$node uncomnt.js
```

Response:
```
/Users/localusr/test/node_modules/extract-comments/lib/comments.js:55
      throw err;
      ^
Error: Line 1: Unexpected token !
    at constructError (/Users/localusr/test/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/localusr/test/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/localusr/test/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/Users/localusr/test/node_modules/esprima/esprima.js:2505:15)
    at consumeSemicolon (/Users/localusr/test/node_modules/esprima/esprima.js:2620:13)
    at parseStatement (/Users/localusr/test/node_modules/esprima/esprima.js:4816:9)
    at parseStatementListItem (/Users/localusr/test/node_modules/esprima/esprima.js:3989:16)
    at parseScriptBody (/Users/localusr/test/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/localusr/test/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/localusr/test/node_modules/esprima/esprima.js:5690:23)

```

**Comment by jonschlinkert** [comment]
this isn't an "exclamation error", it's invalid javascript, which is causing the parser to throw an error.
